version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: config/docker/Dockerfile
    container_name: users_management
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    environment:
      - DB_URL=mongodb://mongodb/usersDB
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db


volumes:
    mongodb_data: